### ISSUE TITLE
Channel Graph incomplete in Uncertainty Graph?

### ISSUE THREAD

**Issue by sebulino** [sebulino/pickhardtpayments#7]
It seems to me as if some nodes are missing in the Uncertainty Graph. 
in 4a13541b34d5489a91292a59163d7639a9c6a994 I'm checking for the existence of the sending node in the networks and send it to logs. 
Needs further investigation.

**Comment by sebulino** [comment]
```
17:37:07.147 | INFO | *** new payment simulation ***
17:37:11.792 | INFO | A total of 1 payments.
Traceback (most recent call last):
  File "/Users/sebulino/Documents/stud/Thesis/Lightning/pickhardtpayments/examples/ChannelDepletionSimulator.py", line 127, in <module>
    logging.warning("ID for MCF of the sender is %s", sim_session.get_mcf_id(testnode))
  File "/Users/sebulino/Documents/stud/Thesis/Lightning/pickhardtpayments/pickhardtpayments/SyncSimulatedPaymentSession.py", line 80, in get_mcf_id
    return self._mcf_id[node_id]
KeyError: '021053940184f66d73ebeb80049d1ce5c3fd176e9c290ff9433aa6f25d839c31fb'
17:37:11.921 | INFO | *********** Payment 1 ***********
17:37:11.921 | WARNING | About node 021053940184f66d73ebeb80049d1ce5c3fd176e9c290ff9433aa6f25d839c31fb:
17:37:11.921 | WARNING | is it in Channel Graph? True
17:37:11.921 | WARNING | is it in Uncertainty Network? False
17:37:11.921 | WARNING | is it in OracleLightningNetwork? True

Process finished with exit code 1
```

**Comment by sebulino** [comment]
In the ChannelGraph, there are only channels with the respective node as a channel destination.
```
cat listchannels20220412.json | grep "021053940184f66d73ebeb80049d1ce5c3fd176e9c290ff9433aa6f25d839c31fb"
         "destination": "021053940184f66d73ebeb80049d1ce5c3fd176e9c290ff9433aa6f25d839c31fb",
         "destination": "021053940184f66d73ebeb80049d1ce5c3fd176e9c290ff9433aa6f25d839c31fb",
```
